#!/usr/bin/env node
/**
 * Extracts the engine slice from dist/kitchen_app.html (data packs + KD + engine fns).
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '../..');
const dist = path.join(root, 'dist/kitchen_app.html');
const out = path.join(__dirname, '../src/engine/engine.generated.js');

const html = fs.readFileSync(dist, 'utf8');
const start = html.indexOf('/*@DATA:INGREDIENTS@*/');
const end = html.indexOf('const state={view:');
if (start < 0 || end < 0 || end <= start) {
  console.error('extract-engine: slice markers not found in', dist);
  process.exit(1);
}

const slice = html.slice(start, end);
const banner = `/* AUTO-GENERATED by scripts/extract-engine.mjs — do not edit.
 * Source: dist/kitchen_app.html [INGREDIENTS..engine]
 * Re-run: npm run extract-engine
 */\n`;

const footer = `
export {
  recipeGraph,
  CATALOG,
  prepClassOf,
  offeredForms,
  transitionsFor,
  exportRecipe,
  topoSteps,
  PREP_CLASS,
};
`;

fs.writeFileSync(out, banner + slice + footer);
console.log('extracted', out);
